services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/workspace/src
      - ./app:/workspace/app
      - ./logs:/workspace/logs
    command: "--port 8000 --reload"
